const servicesData = [
    {
        slug: "business-intelligence",
        title: "Business Intelligence",
        subtitle: "Turn raw data into real-time business clarity",
        icon: "/images/iconbox/icon1.png",
        heroImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
        description: "Get a real-time, unified view of your business performance. We design and build BI environments that give your leadership team the clarity to act fast and with confidence.",
        outcomes: ["Executive dashboards", "KPI tracking", "Performance reporting"],
        overview: "Most businesses are collecting more data than ever — but very few are actually using it to make better decisions. That is the gap Rabok Technologies exists to close. Our Business Intelligence consulting service gives your organisation a clear, real-time view of what is happening across every part of your business, so your leadership team can stop guessing and start deciding with confidence.",
        detail: "We work with you to understand your business model, your key decisions, and the data you already have. Then we design and build a BI environment that surfaces exactly the insights you need — nothing more, nothing less. Every dashboard we build is tied to a specific business question, and every metric we track is connected to an outcome you care about.",
        features: [
            "Current state data audit and gap analysis",
            "KPI definition and metrics framework",
            "Custom dashboard and report design",
            "Data pipeline and integration setup",
            "Team training and adoption support",
            "Ongoing optimisation and support",
        ],
        why: "The businesses that win in the next decade will be the ones that make faster, smarter decisions than their competitors. BI is not a luxury — it is the infrastructure of modern decision-making. Whether you are a growing SME or an established enterprise, having a clear view of your data is the single highest-leverage investment you can make right now.",
    },
    {
        slug: "data-analytics",
        title: "Data Analytics Consulting",
        subtitle: "Uncover the insights hiding in your data",
        icon: "/images/iconbox/icon2.png",
        heroImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80",
        description: "Go beyond surface-level reports. Our analysts dig deep into your data to surface the trends, patterns, and anomalies that reveal exactly where to grow and where to cut.",
        outcomes: ["Root cause analysis", "Trend identification", "Opportunity mapping"],
        overview: "Data analytics is not just about charts and graphs — it is about asking the right questions and finding answers that change how you run your business. Our analytics consultants bring deep technical expertise and genuine business understanding to every engagement.",
        detail: "We start by understanding the decisions you need to make, then work backwards to identify the data and analysis required to make them confidently. Whether you need to understand why sales dropped last quarter, which customer segments are most profitable, or where operational inefficiencies are costing you money — we find the answers.",
        features: [
            "Exploratory data analysis and profiling",
            "Customer segmentation and behaviour analysis",
            "Sales and revenue trend analysis",
            "Operational efficiency analysis",
            "Cohort and funnel analysis",
            "Custom analytical models and frameworks",
        ],
        why: "Most businesses have more data than they know what to do with. The problem is not a lack of data — it is a lack of the right analysis. Our consultants cut through the noise and surface the insights that actually matter to your bottom line.",
    },
    {
        slug: "data-strategy",
        title: "Data Strategy & Roadmap",
        subtitle: "Build a data capability that compounds over time",
        icon: "/images/iconbox/icon3.png",
        heroImage: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&q=80",
        description: "Most businesses collect data but have no plan for it. We build you a clear, actionable data strategy that turns your data into a long-term competitive advantage.",
        outcomes: ["Data maturity assessment", "Technology selection", "Implementation roadmap"],
        overview: "A data strategy is the foundation everything else is built on. Without it, you end up with disconnected tools, siloed data, and analytics that nobody trusts. With it, every investment in data compounds — each new dataset, tool, or capability makes everything else more valuable.",
        detail: "We assess where you are today, define where you need to be, and build a practical roadmap to get there. We help you choose the right tools, define data ownership and governance, and sequence your investments so you get value quickly while building toward a long-term capability.",
        features: [
            "Data maturity assessment",
            "Current state architecture review",
            "Technology stack evaluation and selection",
            "Data governance framework design",
            "Prioritised implementation roadmap",
            "Team capability and hiring plan",
        ],
        why: "Companies that invest in a coherent data strategy consistently outperform those that do not. A clear strategy means less wasted spend, faster time to insight, and a data capability that grows stronger with every passing month.",
    },
    {
        slug: "dashboards-reporting",
        title: "Dashboards & Reporting",
        subtitle: "Dashboards your team will actually use",
        icon: "/images/iconbox/icon4.png",
        heroImage: "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=1200&q=80",
        description: "Custom interactive dashboards your team will actually use — clear, visual, and updated in real time. Built on Power BI, Tableau, Looker, or your preferred platform.",
        outcomes: ["Self-service dashboards", "Automated reports", "Mobile-ready views"],
        overview: "Most dashboards fail not because of bad data, but because they were built for the person who requested them rather than the people who use them. We design dashboards around how your team actually works — what decisions they make, what questions they ask, and how much time they have.",
        detail: "We handle everything from data connection and transformation through to design, testing, and deployment. We also train your team so they can maintain and extend the dashboards themselves — you should not need to call us every time you want to add a new metric.",
        features: [
            "Requirements gathering and user research",
            "Data source connection and transformation",
            "Dashboard design and prototyping",
            "Interactive filters and drill-down views",
            "Automated scheduled reports",
            "Mobile-optimised layouts",
        ],
        why: "A great dashboard pays for itself within weeks. When your team can see the right information at the right time, they make better decisions faster — and that compounds across every part of the business.",
    },
    {
        slug: "data-warehousing",
        title: "Data Warehousing & ETL",
        subtitle: "One source of truth for your entire business",
        icon: "/images/iconbox/icon5.png",
        heroImage: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=1200&q=80",
        description: "Stop working from conflicting spreadsheets. We centralise all your data sources into a single, reliable warehouse so every team is working from the same truth.",
        outcomes: ["Cloud data warehouses", "ETL pipeline design", "Data integration"],
        overview: "If your teams are working from different spreadsheets, pulling data from different systems, and getting different answers to the same question — you have a data infrastructure problem. A well-designed data warehouse solves this by creating a single, reliable source of truth that everyone can trust.",
        detail: "We design and build cloud data warehouses on platforms like BigQuery, Snowflake, Redshift, or Azure Synapse. We also build the ETL pipelines that keep your warehouse up to date — connecting your CRM, ERP, marketing tools, financial systems, and any other data sources into a unified, queryable dataset.",
        features: [
            "Data source inventory and mapping",
            "Cloud data warehouse design and setup",
            "ETL/ELT pipeline development",
            "Data quality monitoring and alerting",
            "Incremental load and scheduling",
            "Documentation and data dictionary",
        ],
        why: "Without a reliable data foundation, every analytics project is built on sand. A well-designed warehouse makes every downstream use of data — dashboards, reports, ML models — faster, cheaper, and more trustworthy.",
    },
    {
        slug: "predictive-analytics",
        title: "Predictive Analytics",
        subtitle: "Know what is coming before your competitors do",
        icon: "/images/iconbox/icon6.png",
        heroImage: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&q=80",
        description: "Know what is coming before it happens. We build predictive models that forecast demand, identify churn risk, and surface revenue opportunities before your competitors see them.",
        outcomes: ["Demand forecasting", "Churn prediction", "Revenue modelling"],
        overview: "Predictive analytics moves you from understanding what happened to anticipating what will happen. When you can forecast demand, predict which customers are about to leave, or identify which leads are most likely to convert — you can act proactively rather than reactively.",
        detail: "We build machine learning models that are practical, explainable, and integrated into your existing workflows. We do not just hand you a model — we make sure it is embedded in the tools your team already uses, with clear outputs that drive real decisions.",
        features: [
            "Demand and sales forecasting",
            "Customer churn prediction",
            "Lead scoring and conversion prediction",
            "Inventory optimisation models",
            "Anomaly detection and alerting",
            "Model monitoring and retraining",
        ],
        why: "Businesses that can anticipate the future have a structural advantage over those that can only react to it. Predictive analytics is no longer the exclusive domain of large enterprises — with the right partner, any business can harness it.",
    },
];

export default servicesData;
